#######
# SITE SETTINGS
#
# title appears in the header
title: Bloom Bhajan
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/ (or look in "_includes/bootstrap-icons")
# some options: code-slash file-code gear tools lightblub book bookmark-star
# title-icon: code-slash
# description appears in sidebar footer
description: "Devotional communications, group songs and lyrics"
# keywords for meta tags used by search engines
keywords: "ayyappa, lyrics, tamil, bhajan"
# image for meta tags, will appear when sharing link on social media
featured-image: "/images/logo.png"

# author name, displayed in credits
author: san6031-repo
# year or date published, displayed in sidebar
publication_year: 2024
# location of code, the full url to your github repository
source-code: https://github.com/sangit6031hub/bloombhajan
# content license (typically "cc by-sa"), displayed in sidebar
content_license: "san6031-repo"
# URL to the content license
content_license_link: https://github.com/sangit6031hub/bloombhajan

##########
# THEME CUSTOMIZATION [optional!]
#
# leave these commented out or blank for defaults.
# these options tweak CSS, so should be valid CSS values.
#
# header-background: 
# header-text-color: 
# breadcrumbs-background: 
# breadcrumbs-text-color: 
# active-nav-color: 
# link-color:
# next-button-color:
# text-color: 
# base-font-size:

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# url:
# use baseurl to add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
# baseurl:


##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "lesson-content"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
